### ISSUE TITLE
Non-jQuery version

### ISSUE THREAD

**Issue by mattdell** [fauxparse/bootstrap-floating-labels#4]
I don't use bootstrap's Javascript functionality, thus I also don't use jQuery in my projects. I wanted to use this but it would require me to convert it out of jQuery syntax and into Vanilla JS. I weighed the options and figured it was worth it.

Here is a first pass at it and this works:

```
var floatingFormGroups = Array.from(document.querySelectorAll('.floating-label-form-group'));

floatingFormGroups.forEach(function(floatingFormGroup) { 

  floatingFormGroup.addEventListener('input', function(e) {
    if (e.target.value && !this.classList.contains('floating-label-form-group-with-value')) {
      this.classList.add('floating-label-form-group-with-value');
    } else if (!e.target.value && this.classList.contains('floating-label-form-group-with-value')) {
      this.classList.remove('floating-label-form-group-with-value');
    }
  });

  floatingFormGroup.addEventListener('focusin', function() {
    this.classList.add('floating-label-form-group-with-focus');
  });

  floatingFormGroup.addEventListener('focusout', function() {
    this.classList.remove('floating-label-form-group-with-focus');
  });
});
```

I thought I'd add it here in case anyone else has this issue. Alternatively it would be great if you'd like to add it into the example @fauxparse to get rid of the jQuery dependency.

**Comment by fauxparse** [comment]
Since Bootstrap itself requires JQuery, I don't think this is unreasonable. I wrote the included JavaScript to follow the conventions of the Bootstrap code.

Additionally, the code you wrote above is not equivalent. It will only find elements present when the script is run, while my original code also works with elements that have been added dynamically.

Thanks for the effort, but I'm not going to merge this code.

**Comment by mattdell** [comment]
Fair enough that it didn't work on dynamically added markup. That was my intention for the next iteration, which I've now done. The updated code would instead be...

```
document.addEventListener('input', function(e) {
  if (e.target.value && e.target.parentElement.classList.contains('floating-label-form-group') && !e.target.parentElement.classList.contains('floating-label-form-group-with-value')) {
    e.target.parentElement.classList.add('floating-label-form-group-with-value');
  } else if (!e.target.value && e.target.parentElement.classList.contains('floating-label-form-group') && e.target.parentElement.classList.contains('floating-label-form-group-with-value')) {
    e.target.parentElement.classList.remove('floating-label-form-group-with-value');
  }
})

document.addEventListener('focusin', function(e) {
  if (e.target.parentElement.classList.contains('floating-label-form-group')) {
    e.target.parentElement.classList.add('floating-label-form-group-with-focus');
  }
});

document.addEventListener('focusout', function(e) {
  if (e.target.parentElement.classList.contains('floating-label-form-group')) {
    e.target.parentElement.classList.remove('floating-label-form-group-with-focus');
  }
});
```

Not all of Bootstrap requires jQuery. Bootstrap plugins require jQuery, but things like Bootstrap grid or Bootstrap forms (which can be downloaded individually) don't use any Bootstrap plugins and only utilize the Bootstrap CSS. While I do agree that your approach is reasonable, it doesn't seem right to enforce a dependency that isn't needed.

More information on Stackoverflow: http://stackoverflow.com/questions/14608681/can-i-use-twitter-bootstrap-without-jquery

Anyway, this is of course your repo so do what you please. If you don't want to merge or include it as an alternative, hopefully this can help somebody else googling for a Vanilla JS alternative. 👍🏻
